In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/Admin/Downloads/indian_liver_patient.csv")

In [3]:
df

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[583 rows x 11 columns]

In [4]:
df.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

# 2 Data preprocessing
# Exploring Dataset
# Encoding 
# Scaling
# Balancing Classes
# feature selection
# train test split

In [5]:
df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [11]:
df.shape

(579, 11)

In [12]:
df.duplicated().sum()

13

# encoding

 When we are doing ML model we required library called sklearn.For the preparing data we used package called preprocessing.
 Then we import two classes labelencoder(for converting text to numbers),ordinalencder(for converting categorical columns in tables into 2 numbers).
 then we created an object of labelencoder
 Here we used a function(encoder.fit_transform) means .fit is used for reading text values and transform is used for converting it into numeric values . 

In [14]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
encoder=LabelEncoder()
df['Gender']=encoder.fit_transform(df['Gender'])


In [15]:
df

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65       0              0.7               0.1                   187   
1     62       1             10.9               5.5                   699   
2     62       1              7.3               4.1                   490   
3     58       1              1.0               0.4                   182   
4     72       1              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60       1              0.5               0.1                   500   
579   40       1              0.6               0.1                    98   
580   52       1              0.8               0.2                   245   
581   31       1              1.3               0.5                   184   
582   38       1              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[579 rows x 11 columns]

# Feature Scaling: scaling is used for to ensures all columns numerical value on a similar range for better model performance because some columns values has higher so it will not take as a similar value.


In [ ]:
# In this we used class standardscaler for making all the columns in similar range

In [17]:
from sklearn.preprocessing import StandardScaler
features=['Age','Total_Bilirubin','Direct_Bilirubin',
          'Alkaline_Phosphotase','Alamine_Aminotransferase',
          'Aspartate_Aminotransferase','Total_Protiens','Albumin',
          'Albumin_and_Globulin_Ratio']
scaler=StandardScaler()
df[features]=scaler.fit_transform(df[features])
df
          

Age  Gender  Total_Bilirubin  Direct_Bilirubin  \
0    1.247403       0        -0.420320         -0.495414   
1    1.062306       1         1.218936          1.423518   
2    1.062306       1         0.640375          0.926017   
3    0.815511       1        -0.372106         -0.388807   
4    1.679294       1         0.093956          0.179766   
..        ...     ...              ...               ...   
578  0.938909       1        -0.452462         -0.495414   
579 -0.295067       1        -0.436391         -0.495414   
580  0.445318       1        -0.404249         -0.459878   
581 -0.850356       1        -0.323893         -0.353271   
582 -0.418465       1        -0.372106         -0.424343   

     Alkaline_Phosphotase  Alamine_Aminotransferase  \
0               -0.428870                 -0.355832   
1                1.675083                 -0.093573   
2                0.816243                 -0.115428   
3               -0.449416                 -0.366760   
4               -0.395996                 -0.295731   
..                    ...                       ...   
578              0.857336                 -0.333977   
579             -0.794596                 -0.252021   
580             -0.190532                 -0.180993   
581             -0.441198                 -0.284804   
582             -0.309701                 -0.328514   

     Aspartate_Aminotransferase  Total_Protiens   Albumin  \
0                     -0.319111        0.293722  0.203446   
1                     -0.035962        0.939655  0.077462   
2                     -0.146459        0.478274  0.203446   
3                     -0.312205        0.293722  0.329431   
4                     -0.177537        0.755102 -0.930414   
..                          ...             ...       ...   
578                   -0.263863       -0.536763 -1.938290   
579                   -0.274222       -0.444487  0.077462   
580                   -0.212067       -0.075383  0.077462   
581                   -0.270769        0.293722  0.329431   
582                   -0.298393        0.755102  1.589276   

     Albumin_and_Globulin_Ratio  Dataset  
0                     -0.147390        1  
1                     -0.648461        1  
2                     -0.178707        1  
3                      0.165780        1  
4                     -1.713237        1  
..                          ...      ...  
578                   -1.807188        2  
579                    0.478949        1  
580                    0.165780        1  
581                    0.165780        1  
582                    1.731627        2  

[579 rows x 11 columns]

# Data Balancing:In this we make the balance of count of disease patient and count of healthy patient 

In [18]:
pip install -q imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [22]:
from imblearn.over_sampling import SMOTE
X=df.drop('Dataset',axis=1)
y=df['Dataset']
smote=SMOTE(random_state=42)
X_resampled,y_resampled=smote.fit_resample(X,y)
y_resampled.value_counts()

Dataset
1    414
2    414
Name: count, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_resampled,y_resampled,test_size=0.2,random_state=42)


# Train model-Logistic regression,svc,decision tree,random forest

# Logistic regression-a specific machine learning algorithm used for classification (predicting categories like Yes/No, 0/1, etc

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report
model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print("\n\n",classification_report(y_test,y_pred))
print("\n\n",confusion_matrix(y_test,y_pred))



               precision    recall  f1-score   support

           1       0.78      0.54      0.64        83
           2       0.65      0.84      0.73        83

    accuracy                           0.69       166
   macro avg       0.71      0.69      0.69       166
weighted avg       0.71      0.69      0.69       166



 [[45 38]
 [13 70]]


# Randomforestclassifier-RandomForestClassifier is a machine learning algorithm from the ensemble family that uses multiple decision trees to perform classification tasks.

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report
model_r=RandomForestClassifier()
model_r.fit(X_train,y_train)
y_pred=model_r.predict(X_test)
print("\n\n",classification_report(y_test,y_pred))
print("\n\n",confusion_matrix(y_test,y_pred))




               precision    recall  f1-score   support

           1       0.95      0.67      0.79        83
           2       0.75      0.96      0.84        83

    accuracy                           0.82       166
   macro avg       0.85      0.82      0.82       166
weighted avg       0.85      0.82      0.82       166



 [[56 27]
 [ 3 80]]


# Support vector classifier-SVC is like a line-drawer it draws the best possible line (or curve) between different categories of data.

In [30]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
model=SVC()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print("\n\n",classification_report(y_test,y_pred))
print("\n\n",confusion_matrix(y_test,y_pred))



               precision    recall  f1-score   support

           1       0.83      0.52      0.64        83
           2       0.65      0.89      0.75        83

    accuracy                           0.70       166
   macro avg       0.74      0.70      0.69       166
weighted avg       0.74      0.70      0.69       166



 [[43 40]
 [ 9 74]]


In [36]:
import numpy as np
np.array([df.iloc[0,:-1]])

array([[ 1.24740264,  0.        , -0.42031984, -0.49541415, -0.42887006,
        -0.35583241, -0.31911128,  0.29372174,  0.20344649, -0.14738974]])

In [46]:
#test1
pred=model_r.predict(np.array([df.iloc[0,:-1]]))
if pred[0]==1:
    print("liver disease")
else:
    print("no disease")
    

liver disease


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [51]:
pred=model_r.predict(np.array([df.iloc[12,:-1]]))
if pred[0]==1:
    print("liver disease")
else:
    print("no disease")
    

no disease


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
